const values = [
    'Pacific/Midway',
    'Pacific/Niue',
    'Pacific/Pago_Pago',
    'America/Adak',
    'Pacific/Honolulu',
    'Pacific/Rarotonga',
    'Pacific/Tahiti',
    'Pacific/Marquesas',
    'America/Anchorage',
    'America/Juneau',
    'America/Metlakatla',
    'America/Nome',
    'America/Sitka',
    'America/Yakutat',
    'Pacific/Gambier',
    'America/Dawson',
    'America/Los_Angeles',
    'America/Tijuana',
    'America/Vancouver',
    'America/Whitehorse',
    'Pacific/Pitcairn',
    'America/Boise',
    'America/Cambridge_Bay',
    'America/Chihuahua',
    'America/Creston',
    'America/Dawson_Creek',
    'America/Denver',
    'America/Edmonton',
    'America/Fort_Nelson',
    'America/Hermosillo',
    'America/Inuvik',
    'America/Mazatlan',
    'America/Ojinaga',
    'America/Phoenix',
    'America/Yellowknife',
    'America/Bahia_Banderas',
    'America/Belize',
    'America/Chicago',
    'America/Costa_Rica',
    'America/El_Salvador',
    'America/Guatemala',
    'America/Indiana/Knox',
    'America/Indiana/Tell_City',
    'America/Managua',
    'America/Matamoros',
    'America/Menominee',
    'America/Merida',
    'America/Mexico_City',
    'America/Monterrey',
    'America/North_Dakota/Beulah',
    'America/North_Dakota/Center',
    'America/North_Dakota/New_Salem',
    'America/Rainy_River',
    'America/Rankin_Inlet',
    'America/Regina',
    'America/Resolute',
    'America/Swift_Current',
    'America/Tegucigalpa',
    'America/Winnipeg',
    'Pacific/Galapagos',
    'America/Atikokan',
    'America/Bogota',
    'America/Cancun',
    'America/Cayman',
    'America/Detroit',
    'America/Eirunepe',
    'America/Grand_Turk',
    'America/Guayaquil',
    'America/Havana',
    'America/Indiana/Indianapolis',
    'America/Indiana/Marengo',
    'America/Indiana/Petersburg',
    'America/Indiana/Vevay',
    'America/Indiana/Vincennes',
    'America/Indiana/Winamac',
    'America/Iqaluit',
    'America/Jamaica',
    'America/Kentucky/Louisville',
    'America/Kentucky/Monticello',
    'America/Lima',
    'America/Nassau',
    'America/New_York',
    'America/Nipigon',
    'America/Panama',
    'America/Pangnirtung',
    'America/Port-au-Prince',
    'America/Rio_Branco',
    'America/Thunder_Bay',
    'America/Toronto',
    'Pacific/Easter',
    'America/Anguilla',
    'America/Antigua',
    'America/Aruba',
    'America/Barbados',
    'America/Blanc-Sablon',
    'America/Boa_Vista',
    'America/Caracas',
    'America/Curacao',
    'America/Dominica',
    'America/Glace_Bay',
    'America/Goose_Bay',
    'America/Grenada',
    'America/Guadeloupe',
    'America/Guyana',
    'America/Halifax',
    'America/Kralendijk',
    'America/La_Paz',
    'America/Lower_Princes',
    'America/Manaus',
    'America/Marigot',
    'America/Martinique',
    'America/Moncton',
    'America/Montserrat',
    'America/Port_of_Spain',
    'America/Porto_Velho',
    'America/Puerto_Rico',
    'America/Santo_Domingo',
    'America/St_Barthelemy',
    'America/St_Kitts',
    'America/St_Lucia',
    'America/St_Thomas',
    'America/St_Vincent',
    'America/Thule',
    'America/Tortola',
    'Atlantic/Bermuda',
    'America/St_Johns',
    'America/Araguaina',
    'America/Argentina/Buenos_Aires',
    'America/Argentina/Catamarca',
    'America/Argentina/Cordoba',
    'America/Argentina/Jujuy',
    'America/Argentina/La_Rioja',
    'America/Argentina/Mendoza',
    'America/Argentina/Rio_Gallegos',
    'America/Argentina/Salta',
    'America/Argentina/San_Juan',
    'America/Argentina/San_Luis',
    'America/Argentina/Tucuman',
    'America/Argentina/Ushuaia',
    'America/Asuncion',
    'America/Bahia',
    'America/Belem',
    'America/Campo_Grande',
    'America/Cayenne',
    'America/Cuiaba',
    'America/Fortaleza',
    'America/Godthab',
    'America/Maceio',
    'America/Miquelon',
    'America/Montevideo',
    'America/Paramaribo',
    'America/Punta_Arenas',
    'America/Recife',
    'America/Santarem',
    'America/Santiago',
    'Antarctica/Palmer',
    'Antarctica/Rothera',
    'Atlantic/Stanley',
    'America/Noronha',
    'America/Sao_Paulo',
    'Atlantic/South_Georgia',
    'America/Scoresbysund',
    'Atlantic/Azores',
    'Atlantic/Cape_Verde',
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Bamako',
    'Africa/Banjul',
    'Africa/Bissau',
    'Africa/Conakry',
    'Africa/Dakar',
    'Africa/Freetown',
    'Africa/Lome',
    'Africa/Monrovia',
    'Africa/Nouakchott',
    'Africa/Ouagadougou',
    'Africa/Sao_Tome',
    'America/Danmarkshavn',
    'Antarctica/Troll',
    'Atlantic/Canary',
    'Atlantic/Faroe',
    'Atlantic/Madeira',
    'Atlantic/Reykjavik',
    'Atlantic/St_Helena',
    'Europe/Dublin',
    'Europe/Guernsey',
    'Europe/Isle_of_Man',
    'Europe/Jersey',
    'Europe/Lisbon',
    'Europe/London',
    'UTC',
    'Africa/Algiers',
    'Africa/Bangui',
    'Africa/Brazzaville',
    'Africa/Casablanca',
    'Africa/Ceuta',
    'Africa/Douala',
    'Africa/El_Aaiun',
    'Africa/Kinshasa',
    'Africa/Lagos',
    'Africa/Libreville',
    'Africa/Luanda',
    'Africa/Malabo',
    'Africa/Ndjamena',
    'Africa/Niamey',
    'Africa/Porto-Novo',
    'Africa/Tunis',
    'Arctic/Longyearbyen',
    'Europe/Amsterdam',
    'Europe/Andorra',
    'Europe/Belgrade',
    'Europe/Berlin',
    'Europe/Bratislava',
    'Europe/Brussels',
    'Europe/Budapest',
    'Europe/Busingen',
    'Europe/Copenhagen',
    'Europe/Gibraltar',
    'Europe/Ljubljana',
    'Europe/Luxembourg',
    'Europe/Madrid',
    'Europe/Malta',
    'Europe/Monaco',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Podgorica',
    'Europe/Prague',
    'Europe/Rome',
    'Europe/San_Marino',
    'Europe/Sarajevo',
    'Europe/Skopje',
    'Europe/Stockholm',
    'Europe/Tirane',
    'Europe/Vaduz',
    'Europe/Vatican',
    'Europe/Vienna',
    'Europe/Warsaw',
    'Europe/Zagreb',
    'Europe/Zurich',
    'Africa/Blantyre',
    'Africa/Bujumbura',
    'Africa/Cairo',
    'Africa/Gaborone',
    'Africa/Harare',
    'Africa/Johannesburg',
    'Africa/Khartoum',
    'Africa/Kigali',
    'Africa/Lubumbashi',
    'Africa/Lusaka',
    'Africa/Maputo',
    'Africa/Maseru',
    'Africa/Mbabane',
    'Africa/Tripoli',
    'Africa/Windhoek',
    'Asia/Amman',
    'Asia/Beirut',
    'Asia/Damascus',
    'Asia/Famagusta',
    'Asia/Gaza',
    'Asia/Hebron',
    'Asia/Jerusalem',
    'Asia/Nicosia',
    'Europe/Athens',
    'Europe/Bucharest',
    'Europe/Chisinau',
    'Europe/Helsinki',
    'Europe/Kaliningrad',
    'Europe/Kiev',
    'Europe/Mariehamn',
    'Europe/Riga',
    'Europe/Sofia',
    'Europe/Tallinn',
    'Europe/Uzhgorod',
    'Europe/Vilnius',
    'Europe/Zaporozhye',
    'Africa/Addis_Ababa',
    'Africa/Asmara',
    'Africa/Dar_es_Salaam',
    'Africa/Djibouti',
    'Africa/Juba',
    'Africa/Kampala',
    'Africa/Mogadishu',
    'Africa/Nairobi',
    'Antarctica/Syowa',
    'Asia/Aden',
    'Asia/Baghdad',
    'Asia/Bahrain',
    'Asia/Kuwait',
    'Asia/Qatar',
    'Asia/Riyadh',
    'Europe/Istanbul',
    'Europe/Kirov',
    'Europe/Minsk',
    'Europe/Moscow',
    'Europe/Simferopol',
    'Indian/Antananarivo',
    'Indian/Comoro',
    'Indian/Mayotte',
    'Asia/Tehran',
    'Asia/Baku',
    'Asia/Dubai',
    'Asia/Muscat',
    'Asia/Tbilisi',
    'Asia/Yerevan',
    'Europe/Astrakhan',
    'Europe/Samara',
    'Europe/Saratov',
    'Europe/Ulyanovsk',
    'Europe/Volgograd',
    'Indian/Mahe',
    'Indian/Mauritius',
    'Indian/Reunion',
    'Asia/Kabul',
    'Antarctica/Mawson',
    'Asia/Aqtau',
    'Asia/Aqtobe',
    'Asia/Ashgabat',
    'Asia/Atyrau',
    'Asia/Dushanbe',
    'Asia/Karachi',
    'Asia/Oral',
    'Asia/Qyzylorda',
    'Asia/Samarkand',
    'Asia/Tashkent',
    'Asia/Yekaterinburg',
    'Indian/Kerguelen',
    'Indian/Maldives',
    'Asia/Colombo',
    'Asia/Kolkata',
    'Asia/Kathmandu',
    'Antarctica/Vostok',
    'Asia/Almaty',
    'Asia/Bishkek',
    'Asia/Dhaka',
    'Asia/Omsk',
    'Asia/Qostanay',
    'Asia/Thimphu',
    'Asia/Urumqi',
    'Indian/Chagos',
    'Asia/Yangon',
    'Indian/Cocos',
    'Antarctica/Davis',
    'Asia/Bangkok',
    'Asia/Barnaul',
    'Asia/Ho_Chi_Minh',
    'Asia/Hovd',
    'Asia/Jakarta',
    'Asia/Krasnoyarsk',
    'Asia/Novokuznetsk',
    'Asia/Novosibirsk',
    'Asia/Phnom_Penh',
    'Asia/Pontianak',
    'Asia/Tomsk',
    'Asia/Vientiane',
    'Indian/Christmas',
    'Antarctica/Casey',
    'Asia/Brunei',
    'Asia/Choibalsan',
    'Asia/Hong_Kong',
    'Asia/Irkutsk',
    'Asia/Kuala_Lumpur',
    'Asia/Kuching',
    'Asia/Macau',
    'Asia/Makassar',
    'Asia/Manila',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Taipei',
    'Asia/Ulaanbaatar',
    'Australia/Perth',
    'Australia/Eucla',
    'Asia/Chita',
    'Asia/Dili',
    'Asia/Jayapura',
    'Asia/Khandyga',
    'Asia/Pyongyang',
    'Asia/Seoul',
    'Asia/Tokyo',
    'Asia/Yakutsk',
    'Pacific/Palau',
    'Australia/Darwin',
    'Antarctica/DumontDUrville',
    'Asia/Ust-Nera',
    'Asia/Vladivostok',
    'Australia/Brisbane',
    'Australia/Lindeman',
    'Pacific/Chuuk',
    'Pacific/Guam',
    'Pacific/Port_Moresby',
    'Pacific/Saipan',
    'Australia/Adelaide',
    'Australia/Broken_Hill',
    'Antarctica/Macquarie',
    'Asia/Magadan',
    'Asia/Sakhalin',
    'Asia/Srednekolymsk',
    'Australia/Currie',
    'Australia/Hobart',
    'Australia/Lord_Howe',
    'Australia/Melbourne',
    'Australia/Sydney',
    'Pacific/Bougainville',
    'Pacific/Efate',
    'Pacific/Guadalcanal',
    'Pacific/Kosrae',
    'Pacific/Norfolk',
    'Pacific/Noumea',
    'Pacific/Pohnpei',
    'Asia/Anadyr',
    'Asia/Kamchatka',
    'Pacific/Funafuti',
    'Pacific/Kwajalein',
    'Pacific/Majuro',
    'Pacific/Nauru',
    'Pacific/Tarawa',
    'Pacific/Wake',
    'Pacific/Wallis',
    'Antarctica/McMurdo',
    'Pacific/Auckland',
    'Pacific/Enderbury',
    'Pacific/Fakaofo',
    'Pacific/Fiji',
    'Pacific/Tongatapu',
    'Pacific/Chatham',
    'Pacific/Apia',
    'Pacific/Kiritimati'
];

const displays = [
    '(UTC-11:00) Pacific, Midway',
    '(UTC-11:00) Pacific, Niue',
    '(UTC-11:00) Pacific, Pago Pago',
    '(UTC-10:00) America, Adak',
    '(UTC-10:00) Pacific, Honolulu',
    '(UTC-10:00) Pacific, Rarotonga',
    '(UTC-10:00) Pacific, Tahiti',
    '(UTC-09:30) Pacific, Marquesas',
    '(UTC-09:00) America, Anchorage',
    '(UTC-09:00) America, Juneau',
    '(UTC-09:00) America, Metlakatla',
    '(UTC-09:00) America, Nome',
    '(UTC-09:00) America, Sitka',
    '(UTC-09:00) America, Yakutat',
    '(UTC-09:00) Pacific, Gambier',
    '(UTC-08:00) America, Dawson',
    '(UTC-08:00) America, Los Angeles',
    '(UTC-08:00) America, Tijuana',
    '(UTC-08:00) America, Vancouver',
    '(UTC-08:00) America, Whitehorse',
    '(UTC-08:00) Pacific, Pitcairn',
    '(UTC-07:00) America, Boise',
    '(UTC-07:00) America, Cambridge Bay',
    '(UTC-07:00) America, Chihuahua',
    '(UTC-07:00) America, Creston',
    '(UTC-07:00) America, Dawson Creek',
    '(UTC-07:00) America, Denver',
    '(UTC-07:00) America, Edmonton',
    '(UTC-07:00) America, Fort Nelson',
    '(UTC-07:00) America, Hermosillo',
    '(UTC-07:00) America, Inuvik',
    '(UTC-07:00) America, Mazatlan',
    '(UTC-07:00) America, Ojinaga',
    '(UTC-07:00) America, Phoenix',
    '(UTC-07:00) America, Yellowknife',
    '(UTC-06:00) America, Bahia Banderas',
    '(UTC-06:00) America, Belize',
    '(UTC-06:00) America, Chicago',
    '(UTC-06:00) America, Costa Rica',
    '(UTC-06:00) America, El Salvador',
    '(UTC-06:00) America, Guatemala',
    '(UTC-06:00) America, Indiana, Knox',
    '(UTC-06:00) America, Indiana, Tell City',
    '(UTC-06:00) America, Managua',
    '(UTC-06:00) America, Matamoros',
    '(UTC-06:00) America, Menominee',
    '(UTC-06:00) America, Merida',
    '(UTC-06:00) America, Mexico City',
    '(UTC-06:00) America, Monterrey',
    '(UTC-06:00) America, North Dakota, Beulah',
    '(UTC-06:00) America, North Dakota, Center',
    '(UTC-06:00) America, North Dakota, New Salem',
    '(UTC-06:00) America, Rainy River',
    '(UTC-06:00) America, Rankin Inlet',
    '(UTC-06:00) America, Regina',
    '(UTC-06:00) America, Resolute',
    '(UTC-06:00) America, Swift Current',
    '(UTC-06:00) America, Tegucigalpa',
    '(UTC-06:00) America, Winnipeg',
    '(UTC-06:00) Pacific, Galapagos',
    '(UTC-05:00) America, Atikokan',
    '(UTC-05:00) America, Bogota',
    '(UTC-05:00) America, Cancun',
    '(UTC-05:00) America, Cayman',
    '(UTC-05:00) America, Detroit',
    '(UTC-05:00) America, Eirunepe',
    '(UTC-05:00) America, Grand Turk',
    '(UTC-05:00) America, Guayaquil',
    '(UTC-05:00) America, Havana',
    '(UTC-05:00) America, Indiana, Indianapolis',
    '(UTC-05:00) America, Indiana, Marengo',
    '(UTC-05:00) America, Indiana, Petersburg',
    '(UTC-05:00) America, Indiana, Vevay',
    '(UTC-05:00) America, Indiana, Vincennes',
    '(UTC-05:00) America, Indiana, Winamac',
    '(UTC-05:00) America, Iqaluit',
    '(UTC-05:00) America, Jamaica',
    '(UTC-05:00) America, Kentucky, Louisville',
    '(UTC-05:00) America, Kentucky, Monticello',
    '(UTC-05:00) America, Lima',
    '(UTC-05:00) America, Nassau',
    '(UTC-05:00) America, New York',
    '(UTC-05:00) America, Nipigon',
    '(UTC-05:00) America, Panama',
    '(UTC-05:00) America, Pangnirtung',
    '(UTC-05:00) America, Port-au-Prince',
    '(UTC-05:00) America, Rio Branco',
    '(UTC-05:00) America, Thunder Bay',
    '(UTC-05:00) America, Toronto',
    '(UTC-05:00) Pacific, Easter',
    '(UTC-04:00) America, Anguilla',
    '(UTC-04:00) America, Antigua',
    '(UTC-04:00) America, Aruba',
    '(UTC-04:00) America, Barbados',
    '(UTC-04:00) America, Blanc-Sablon',
    '(UTC-04:00) America, Boa Vista',
    '(UTC-04:00) America, Caracas',
    '(UTC-04:00) America, Curacao',
    '(UTC-04:00) America, Dominica',
    '(UTC-04:00) America, Glace Bay',
    '(UTC-04:00) America, Goose Bay',
    '(UTC-04:00) America, Grenada',
    '(UTC-04:00) America, Guadeloupe',
    '(UTC-04:00) America, Guyana',
    '(UTC-04:00) America, Halifax',
    '(UTC-04:00) America, Kralendijk',
    '(UTC-04:00) America, La Paz',
    '(UTC-04:00) America, Lower Princes',
    '(UTC-04:00) America, Manaus',
    '(UTC-04:00) America, Marigot',
    '(UTC-04:00) America, Martinique',
    '(UTC-04:00) America, Moncton',
    '(UTC-04:00) America, Montserrat',
    '(UTC-04:00) America, Port of Spain',
    '(UTC-04:00) America, Porto Velho',
    '(UTC-04:00) America, Puerto Rico',
    '(UTC-04:00) America, Santo Domingo',
    '(UTC-04:00) America, St. Barthelemy',
    '(UTC-04:00) America, St. Kitts',
    '(UTC-04:00) America, St. Lucia',
    '(UTC-04:00) America, St. Thomas',
    '(UTC-04:00) America, St. Vincent',
    '(UTC-04:00) America, Thule',
    '(UTC-04:00) America, Tortola',
    '(UTC-04:00) Atlantic, Bermuda',
    '(UTC-03:30) America, St. Johns',
    '(UTC-03:00) America, Araguaina',
    '(UTC-03:00) America, Argentina, Buenos Aires',
    '(UTC-03:00) America, Argentina, Catamarca',
    '(UTC-03:00) America, Argentina, Cordoba',
    '(UTC-03:00) America, Argentina, Jujuy',
    '(UTC-03:00) America, Argentina, La Rioja',
    '(UTC-03:00) America, Argentina, Mendoza',
    '(UTC-03:00) America, Argentina, Rio Gallegos',
    '(UTC-03:00) America, Argentina, Salta',
    '(UTC-03:00) America, Argentina, San Juan',
    '(UTC-03:00) America, Argentina, San Luis',
    '(UTC-03:00) America, Argentina, Tucuman',
    '(UTC-03:00) America, Argentina, Ushuaia',
    '(UTC-03:00) America, Asuncion',
    '(UTC-03:00) America, Bahia',
    '(UTC-03:00) America, Belem',
    '(UTC-03:00) America, Campo Grande',
    '(UTC-03:00) America, Cayenne',
    '(UTC-03:00) America, Cuiaba',
    '(UTC-03:00) America, Fortaleza',
    '(UTC-03:00) America, Godthab',
    '(UTC-03:00) America, Maceio',
    '(UTC-03:00) America, Miquelon',
    '(UTC-03:00) America, Montevideo',
    '(UTC-03:00) America, Paramaribo',
    '(UTC-03:00) America, Punta Arenas',
    '(UTC-03:00) America, Recife',
    '(UTC-03:00) America, Santarem',
    '(UTC-03:00) America, Santiago',
    '(UTC-03:00) Antarctica, Palmer',
    '(UTC-03:00) Antarctica, Rothera',
    '(UTC-03:00) Atlantic, Stanley',
    '(UTC-02:00) America, Noronha',
    '(UTC-02:00) America, Sao Paulo',
    '(UTC-02:00) Atlantic, South Georgia',
    '(UTC-01:00) America, Scoresbysund',
    '(UTC-01:00) Atlantic, Azores',
    '(UTC-01:00) Atlantic, Cape Verde',
    '(UTC) Africa, Abidjan',
    '(UTC) Africa, Accra',
    '(UTC) Africa, Bamako',
    '(UTC) Africa, Banjul',
    '(UTC) Africa, Bissau',
    '(UTC) Africa, Conakry',
    '(UTC) Africa, Dakar',
    '(UTC) Africa, Freetown',
    '(UTC) Africa, Lome',
    '(UTC) Africa, Monrovia',
    '(UTC) Africa, Nouakchott',
    '(UTC) Africa, Ouagadougou',
    '(UTC) Africa, Sao Tome',
    '(UTC) America, Danmarkshavn',
    '(UTC) Antarctica, Troll',
    '(UTC) Atlantic, Canary',
    '(UTC) Atlantic, Faroe',
    '(UTC) Atlantic, Madeira',
    '(UTC) Atlantic, Reykjavik',
    '(UTC) Atlantic, St. Helena',
    '(UTC) Europe, Dublin',
    '(UTC) Europe, Guernsey',
    '(UTC) Europe, Isle of Man',
    '(UTC) Europe, Jersey',
    '(UTC) Europe, Lisbon',
    '(UTC) Europe, London',
    '(UTC) UTC',
    '(UTC+01:00) Africa, Algiers',
    '(UTC+01:00) Africa, Bangui',
    '(UTC+01:00) Africa, Brazzaville',
    '(UTC+01:00) Africa, Casablanca',
    '(UTC+01:00) Africa, Ceuta',
    '(UTC+01:00) Africa, Douala',
    '(UTC+01:00) Africa, El Aaiun',
    '(UTC+01:00) Africa, Kinshasa',
    '(UTC+01:00) Africa, Lagos',
    '(UTC+01:00) Africa, Libreville',
    '(UTC+01:00) Africa, Luanda',
    '(UTC+01:00) Africa, Malabo',
    '(UTC+01:00) Africa, Ndjamena',
    '(UTC+01:00) Africa, Niamey',
    '(UTC+01:00) Africa, Porto-Novo',
    '(UTC+01:00) Africa, Tunis',
    '(UTC+01:00) Arctic, Longyearbyen',
    '(UTC+01:00) Europe, Amsterdam',
    '(UTC+01:00) Europe, Andorra',
    '(UTC+01:00) Europe, Belgrade',
    '(UTC+01:00) Europe, Berlin',
    '(UTC+01:00) Europe, Bratislava',
    '(UTC+01:00) Europe, Brussels',
    '(UTC+01:00) Europe, Budapest',
    '(UTC+01:00) Europe, Busingen',
    '(UTC+01:00) Europe, Copenhagen',
    '(UTC+01:00) Europe, Gibraltar',
    '(UTC+01:00) Europe, Ljubljana',
    '(UTC+01:00) Europe, Luxembourg',
    '(UTC+01:00) Europe, Madrid',
    '(UTC+01:00) Europe, Malta',
    '(UTC+01:00) Europe, Monaco',
    '(UTC+01:00) Europe, Oslo',
    '(UTC+01:00) Europe, Paris',
    '(UTC+01:00) Europe, Podgorica',
    '(UTC+01:00) Europe, Prague',
    '(UTC+01:00) Europe, Rome',
    '(UTC+01:00) Europe, San Marino',
    '(UTC+01:00) Europe, Sarajevo',
    '(UTC+01:00) Europe, Skopje',
    '(UTC+01:00) Europe, Stockholm',
    '(UTC+01:00) Europe, Tirane',
    '(UTC+01:00) Europe, Vaduz',
    '(UTC+01:00) Europe, Vatican',
    '(UTC+01:00) Europe, Vienna',
    '(UTC+01:00) Europe, Warsaw',
    '(UTC+01:00) Europe, Zagreb',
    '(UTC+01:00) Europe, Zurich',
    '(UTC+02:00) Africa, Blantyre',
    '(UTC+02:00) Africa, Bujumbura',
    '(UTC+02:00) Africa, Cairo',
    '(UTC+02:00) Africa, Gaborone',
    '(UTC+02:00) Africa, Harare',
    '(UTC+02:00) Africa, Johannesburg',
    '(UTC+02:00) Africa, Khartoum',
    '(UTC+02:00) Africa, Kigali',
    '(UTC+02:00) Africa, Lubumbashi',
    '(UTC+02:00) Africa, Lusaka',
    '(UTC+02:00) Africa, Maputo',
    '(UTC+02:00) Africa, Maseru',
    '(UTC+02:00) Africa, Mbabane',
    '(UTC+02:00) Africa, Tripoli',
    '(UTC+02:00) Africa, Windhoek',
    '(UTC+02:00) Asia, Amman',
    '(UTC+02:00) Asia, Beirut',
    '(UTC+02:00) Asia, Damascus',
    '(UTC+02:00) Asia, Famagusta',
    '(UTC+02:00) Asia, Gaza',
    '(UTC+02:00) Asia, Hebron',
    '(UTC+02:00) Asia, Jerusalem',
    '(UTC+02:00) Asia, Nicosia',
    '(UTC+02:00) Europe, Athens',
    '(UTC+02:00) Europe, Bucharest',
    '(UTC+02:00) Europe, Chisinau',
    '(UTC+02:00) Europe, Helsinki',
    '(UTC+02:00) Europe, Kaliningrad',
    '(UTC+02:00) Europe, Kiev',
    '(UTC+02:00) Europe, Mariehamn',
    '(UTC+02:00) Europe, Riga',
    '(UTC+02:00) Europe, Sofia',
    '(UTC+02:00) Europe, Tallinn',
    '(UTC+02:00) Europe, Uzhgorod',
    '(UTC+02:00) Europe, Vilnius',
    '(UTC+02:00) Europe, Zaporozhye',
    '(UTC+03:00) Africa, Addis Ababa',
    '(UTC+03:00) Africa, Asmara',
    '(UTC+03:00) Africa, Dar es Salaam',
    '(UTC+03:00) Africa, Djibouti',
    '(UTC+03:00) Africa, Juba',
    '(UTC+03:00) Africa, Kampala',
    '(UTC+03:00) Africa, Mogadishu',
    '(UTC+03:00) Africa, Nairobi',
    '(UTC+03:00) Antarctica, Syowa',
    '(UTC+03:00) Asia, Aden',
    '(UTC+03:00) Asia, Baghdad',
    '(UTC+03:00) Asia, Bahrain',
    '(UTC+03:00) Asia, Kuwait',
    '(UTC+03:00) Asia, Qatar',
    '(UTC+03:00) Asia, Riyadh',
    '(UTC+03:00) Europe, Istanbul',
    '(UTC+03:00) Europe, Kirov',
    '(UTC+03:00) Europe, Minsk',
    '(UTC+03:00) Europe, Moscow',
    '(UTC+03:00) Europe, Simferopol',
    '(UTC+03:00) Indian, Antananarivo',
    '(UTC+03:00) Indian, Comoro',
    '(UTC+03:00) Indian, Mayotte',
    '(UTC+03:30) Asia, Tehran',
    '(UTC+04:00) Asia, Baku',
    '(UTC+04:00) Asia, Dubai',
    '(UTC+04:00) Asia, Muscat',
    '(UTC+04:00) Asia, Tbilisi',
    '(UTC+04:00) Asia, Yerevan',
    '(UTC+04:00) Europe, Astrakhan',
    '(UTC+04:00) Europe, Samara',
    '(UTC+04:00) Europe, Saratov',
    '(UTC+04:00) Europe, Ulyanovsk',
    '(UTC+04:00) Europe, Volgograd',
    '(UTC+04:00) Indian, Mahe',
    '(UTC+04:00) Indian, Mauritius',
    '(UTC+04:00) Indian, Reunion',
    '(UTC+04:30) Asia, Kabul',
    '(UTC+05:00) Antarctica, Mawson',
    '(UTC+05:00) Asia, Aqtau',
    '(UTC+05:00) Asia, Aqtobe',
    '(UTC+05:00) Asia, Ashgabat',
    '(UTC+05:00) Asia, Atyrau',
    '(UTC+05:00) Asia, Dushanbe',
    '(UTC+05:00) Asia, Karachi',
    '(UTC+05:00) Asia, Oral',
    '(UTC+05:00) Asia, Qyzylorda',
    '(UTC+05:00) Asia, Samarkand',
    '(UTC+05:00) Asia, Tashkent',
    '(UTC+05:00) Asia, Yekaterinburg',
    '(UTC+05:00) Indian, Kerguelen',
    '(UTC+05:00) Indian, Maldives',
    '(UTC+05:30) Asia, Colombo',
    '(UTC+05:30) Asia, Kolkata',
    '(UTC+05:45) Asia, Kathmandu',
    '(UTC+06:00) Antarctica, Vostok',
    '(UTC+06:00) Asia, Almaty',
    '(UTC+06:00) Asia, Bishkek',
    '(UTC+06:00) Asia, Dhaka',
    '(UTC+06:00) Asia, Omsk',
    '(UTC+06:00) Asia, Qostanay',
    '(UTC+06:00) Asia, Thimphu',
    '(UTC+06:00) Asia, Urumqi',
    '(UTC+06:00) Indian, Chagos',
    '(UTC+06:30) Asia, Yangon',
    '(UTC+06:30) Indian, Cocos',
    '(UTC+07:00) Antarctica, Davis',
    '(UTC+07:00) Asia, Bangkok',
    '(UTC+07:00) Asia, Barnaul',
    '(UTC+07:00) Asia, Ho Chi Minh',
    '(UTC+07:00) Asia, Hovd',
    '(UTC+07:00) Asia, Jakarta',
    '(UTC+07:00) Asia, Krasnoyarsk',
    '(UTC+07:00) Asia, Novokuznetsk',
    '(UTC+07:00) Asia, Novosibirsk',
    '(UTC+07:00) Asia, Phnom Penh',
    '(UTC+07:00) Asia, Pontianak',
    '(UTC+07:00) Asia, Tomsk',
    '(UTC+07:00) Asia, Vientiane',
    '(UTC+07:00) Indian, Christmas',
    '(UTC+08:00) Antarctica, Casey',
    '(UTC+08:00) Asia, Brunei',
    '(UTC+08:00) Asia, Choibalsan',
    '(UTC+08:00) Asia, Hong Kong',
    '(UTC+08:00) Asia, Irkutsk',
    '(UTC+08:00) Asia, Kuala Lumpur',
    '(UTC+08:00) Asia, Kuching',
    '(UTC+08:00) Asia, Macau',
    '(UTC+08:00) Asia, Makassar',
    '(UTC+08:00) Asia, Manila',
    '(UTC+08:00) Asia, Shanghai',
    '(UTC+08:00) Asia, Singapore',
    '(UTC+08:00) Asia, Taipei',
    '(UTC+08:00) Asia, Ulaanbaatar',
    '(UTC+08:00) Australia, Perth',
    '(UTC+08:45) Australia, Eucla',
    '(UTC+09:00) Asia, Chita',
    '(UTC+09:00) Asia, Dili',
    '(UTC+09:00) Asia, Jayapura',
    '(UTC+09:00) Asia, Khandyga',
    '(UTC+09:00) Asia, Pyongyang',
    '(UTC+09:00) Asia, Seoul',
    '(UTC+09:00) Asia, Tokyo',
    '(UTC+09:00) Asia, Yakutsk',
    '(UTC+09:00) Pacific, Palau',
    '(UTC+09:30) Australia, Darwin',
    '(UTC+10:00) Antarctica, DumontDUrville',
    '(UTC+10:00) Asia, Ust-Nera',
    '(UTC+10:00) Asia, Vladivostok',
    '(UTC+10:00) Australia, Brisbane',
    '(UTC+10:00) Australia, Lindeman',
    '(UTC+10:00) Pacific, Chuuk',
    '(UTC+10:00) Pacific, Guam',
    '(UTC+10:00) Pacific, Port Moresby',
    '(UTC+10:00) Pacific, Saipan',
    '(UTC+10:30) Australia, Adelaide',
    '(UTC+10:30) Australia, Broken Hill',
    '(UTC+11:00) Antarctica, Macquarie',
    '(UTC+11:00) Asia, Magadan',
    '(UTC+11:00) Asia, Sakhalin',
    '(UTC+11:00) Asia, Srednekolymsk',
    '(UTC+11:00) Australia, Currie',
    '(UTC+11:00) Australia, Hobart',
    '(UTC+11:00) Australia, Lord Howe',
    '(UTC+11:00) Australia, Melbourne',
    '(UTC+11:00) Australia, Sydney',
    '(UTC+11:00) Pacific, Bougainville',
    '(UTC+11:00) Pacific, Efate',
    '(UTC+11:00) Pacific, Guadalcanal',
    '(UTC+11:00) Pacific, Kosrae',
    '(UTC+11:00) Pacific, Norfolk',
    '(UTC+11:00) Pacific, Noumea',
    '(UTC+11:00) Pacific, Pohnpei',
    '(UTC+12:00) Asia, Anadyr',
    '(UTC+12:00) Asia, Kamchatka',
    '(UTC+12:00) Pacific, Funafuti',
    '(UTC+12:00) Pacific, Kwajalein',
    '(UTC+12:00) Pacific, Majuro',
    '(UTC+12:00) Pacific, Nauru',
    '(UTC+12:00) Pacific, Tarawa',
    '(UTC+12:00) Pacific, Wake',
    '(UTC+12:00) Pacific, Wallis',
    '(UTC+13:00) Antarctica, McMurdo',
    '(UTC+13:00) Pacific, Auckland',
    '(UTC+13:00) Pacific, Enderbury',
    '(UTC+13:00) Pacific, Fakaofo',
    '(UTC+13:00) Pacific, Fiji',
    '(UTC+13:00) Pacific, Tongatapu',
    '(UTC+13:45) Pacific, Chatham',
    '(UTC+14:00) Pacific, Apia',
    '(UTC+14:00) Pacific, Kiritimati'
];

const availableTimezones = [];

for (let i = 0; i < values.length; i++) {
    availableTimezones.push({
        value: values[i],
        display: displays[i]
    })
}

export default availableTimezones;
